import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

import { byteLength } from "./text.mjs";

export const CATALOG_OPEN = "<!-- acp-catalog:";
export const CATALOG_CLOSE = "<!-- /acp-catalog -->";
const KIND_ORDER = { gate: 0, advice: 1, fact: 2 };

/**
 * Render the always-on catalog: one hook line per active rule grouped by
 * repo and operation, then STATE entries with their expiry dates. This is
 * the only context that every session sees without deciding to read.
 */
export function renderCatalog(workspace, { renderedAt = new Date().toISOString(), kitVersion } = {}) {
  const { rules, state, config } = workspace;
  const version = kitVersion ?? config.kit_version;
  const lines = [];
  lines.push("## Workspace Context Catalog");
  lines.push("");
  lines.push(
    "Grouped by repo and operation. Before acting, read the body of every entry that matches the task: " +
      "`.agent-context/rules/<id>.md`, or run `evolve select` with a task signature. Report the ids you used " +
      "in the evolve receipt. Generated by evolve; do not edit by hand.",
  );

  const groups = new Map();
  for (const rule of rules) {
    const repo = rule.applies_to.repos[0] ?? "any";
    const op = rule.applies_to.ops[0] ?? "general";
    const key = `${repo} · ${op}`;
    if (!groups.has(key)) groups.set(key, { repo, op, rules: [] });
    groups.get(key).rules.push(rule);
  }
  const orderedGroups = [...groups.values()].sort((left, right) => {
    if (left.repo === "any" && right.repo !== "any") return 1;
    if (left.repo !== "any" && right.repo === "any") return -1;
    return left.repo.localeCompare(right.repo) || left.op.localeCompare(right.op);
  });
  for (const group of orderedGroups) {
    lines.push("");
    lines.push(`### ${group.repo} · ${group.op}`);
    for (const rule of sortRules(group.rules)) {
      lines.push(`- ${rule.kind} [${rule.id}] ${rule.hook}`);
    }
  }

  const activeState = state
    .filter((entry) => entry.expires >= workspace.today)
    .sort((left, right) => left.expires.localeCompare(right.expires) || left.id.localeCompare(right.id));
  if (activeState.length > 0) {
    lines.push("");
    lines.push("### STATE (auto-expires)");
    for (const entry of activeState) {
      const repos = entry.repos.length > 0 ? `${entry.repos.join(",")}: ` : "";
      lines.push(`- (${entry.expires.slice(5)}) ${repos}${entry.text}`);
    }
  }

  const body = lines.join("\n");
  const header = `${CATALOG_OPEN} kit=${version} schema=2 rendered=${renderedAt} rules=${rules.length} state=${activeState.length} -->`;
  const text = `${header}\n${body}\n${CATALOG_CLOSE}\n`;
  return { text, bytes: byteLength(text), rules: rules.length, state: activeState.length };
}

export function sortRules(rules) {
  return [...rules].sort(
    (left, right) =>
      KIND_ORDER[left.kind] - KIND_ORDER[right.kind] ||
      right.consulted - left.consulted ||
      left.id.localeCompare(right.id),
  );
}

/** Replace (or append) the managed block inside an instruction file's text. */
export function replaceCatalogBlock(source, catalogText) {
  const normalized = source.replaceAll("\r\n", "\n");
  const start = normalized.indexOf(CATALOG_OPEN);
  const end = normalized.indexOf(CATALOG_CLOSE);
  if (start === -1 && end === -1) {
    const separator = normalized === "" ? "" : normalized.endsWith("\n\n") ? "" : normalized.endsWith("\n") ? "\n" : "\n\n";
    return `${normalized}${separator}${catalogText}`;
  }
  if (start === -1 || end === -1 || end < start) {
    throw new Error("instruction file has an unbalanced acp-catalog block");
  }
  const blockEnd = end + CATALOG_CLOSE.length;
  const trailing = normalized[blockEnd] === "\n" ? blockEnd + 1 : blockEnd;
  return `${normalized.slice(0, start)}${catalogText}${normalized.slice(trailing)}`;
}

export async function writeCatalog(workspace, options = {}) {
  const catalog = renderCatalog(workspace, options);
  const agentsPath = join(workspace.workspaceRoot, workspace.config.agents_file);
  let source = "";
  try {
    source = await readFile(agentsPath, "utf8");
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
  const next = replaceCatalogBlock(source, catalog.text);
  if (next !== source) await writeFile(agentsPath, next, "utf8");
  return { ...catalog, agentsPath, changed: next !== source };
}
