import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

import { parseFrontmatter } from "./yaml.mjs";

const MANAGED_HEADER = "<!-- acp-memory: generated by evolve; workspace rules and state live in the AGENTS.md catalog -->";
const KEEP_TYPES = new Set(["user"]);

/**
 * Bridge Claude Code's per-project auto-memory to the workspace. Memory
 * files typed `feedback` or `project` are workspace knowledge and belong in
 * rules or STATE; only `user` memories stay indexed here. The index file
 * becomes a generated view so the two agents read one source.
 */
export async function scanMemory(memoryDir) {
  let entries;
  try {
    entries = await readdir(memoryDir, { withFileTypes: true });
  } catch (error) {
    if (error?.code === "ENOENT") return { status: "missing", files: [] };
    throw error;
  }
  const files = [];
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith(".md") || entry.name === "MEMORY.md") continue;
    const source = await readFile(join(memoryDir, entry.name), "utf8");
    let data = {};
    try {
      data = parseFrontmatter(source, entry.name).data;
    } catch {
      // untyped memory stays a candidate for migration
    }
    files.push({
      file: entry.name,
      name: typeof data.name === "string" ? data.name : entry.name.replace(/\.md$/u, ""),
      description: typeof data.description === "string" ? data.description : "",
      type: typeof data.metadata?.type === "string" ? data.metadata.type : "untyped",
    });
  }
  files.sort((left, right) => left.file.localeCompare(right.file));
  return {
    status: "ok",
    files,
    keep: files.filter((file) => KEEP_TYPES.has(file.type)),
    candidates: files.filter((file) => !KEEP_TYPES.has(file.type)),
  };
}

export function renderMemoryIndex({ keep }) {
  const lines = [MANAGED_HEADER, "# Memory Index", ""];
  lines.push("Workspace rules and dated state are in the `acp-catalog` block of AGENTS.md; do not duplicate them here.");
  lines.push("Save only `user` memories (who the user is) in this directory. Reusable lessons go through `evolve apply`; dated status goes to STATE.");
  lines.push("");
  for (const file of keep) lines.push(`- [${file.name}](${file.file}) — ${file.description}`);
  return `${lines.join("\n")}\n`;
}

export async function syncMemoryIndex({ memoryDir, write = true }) {
  const scan = await scanMemory(memoryDir);
  if (scan.status !== "ok") return scan;
  const index = renderMemoryIndex(scan);
  const indexPath = join(memoryDir, "MEMORY.md");
  let changed = false;
  if (write) {
    let current = "";
    try {
      current = await readFile(indexPath, "utf8");
    } catch {
      // first render
    }
    if (current !== index) {
      await writeFile(indexPath, index, "utf8");
      changed = true;
    }
  }
  return { status: "ok", indexPath, changed, keep: scan.keep, candidates: scan.candidates, index };
}
