import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import { scanMemory, syncMemoryIndex } from "../../skills/evolve/runtime/index.mjs";

test("memory bridge keeps user memories in the index and reports the rest as migration candidates", async () => {
  const memoryDir = mkdtempSync(join(tmpdir(), "acp-memory-"));
  try {
    writeFileSync(join(memoryDir, "who.md"), "---\nname: who-i-am\ndescription: role and preferences\nmetadata:\n  type: user\n---\n\nbody\n", "utf8");
    writeFileSync(join(memoryDir, "lesson.md"), "---\nname: a-lesson\ndescription: a workflow lesson\nmetadata:\n  type: feedback\n---\n\nbody\n", "utf8");
    writeFileSync(join(memoryDir, "untyped.md"), "no frontmatter here\n", "utf8");
    writeFileSync(join(memoryDir, "MEMORY.md"), "- stale index\n", "utf8");

    const scan = await scanMemory(memoryDir);
    assert.deepEqual(scan.keep.map((file) => file.name), ["who-i-am"]);
    assert.deepEqual(scan.candidates.map((file) => [file.file, file.type]), [["lesson.md", "feedback"], ["untyped.md", "untyped"]]);

    const dry = await syncMemoryIndex({ memoryDir, write: false });
    assert.equal(dry.changed, false);
    assert.equal(readFileSync(join(memoryDir, "MEMORY.md"), "utf8"), "- stale index\n");

    const sync = await syncMemoryIndex({ memoryDir });
    assert.equal(sync.changed, true);
    const index = readFileSync(join(memoryDir, "MEMORY.md"), "utf8");
    assert.match(index, /^<!-- acp-memory: generated by evolve/u);
    assert.match(index, /- \[who-i-am\]\(who\.md\) — role and preferences/u);
    assert.ok(!index.includes("a-lesson"));
    const again = await syncMemoryIndex({ memoryDir });
    assert.equal(again.changed, false);
    assert.equal((await scanMemory(join(memoryDir, "missing"))).status, "missing");
  } finally {
    rmSync(memoryDir, { recursive: true, force: true });
  }
});
